// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2mTq1u8uig8HIWpHjDF30E-_gUs6wi4',
    appId: '1:138006115795:web:dab219fac0797c7ad3ab26',
    messagingSenderId: '138006115795',
    projectId: 'eentrack-version-2',
    authDomain: 'eentrack-version-2.firebaseapp.com',
    storageBucket: 'eentrack-version-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78xC4kPF4HzcqAmbxQraSphVPxcZO-Hk',
    appId: '1:138006115795:android:3dc335016ca2daecd3ab26',
    messagingSenderId: '138006115795',
    projectId: 'eentrack-version-2',
    storageBucket: 'eentrack-version-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKnB5NnAKjyetB78PKgbLDPaNYCCMKrQ',
    appId: '1:138006115795:ios:2b7b0a87f237ecbed3ab26',
    messagingSenderId: '138006115795',
    projectId: 'eentrack-version-2',
    storageBucket: 'eentrack-version-2.appspot.com',
    iosBundleId: 'com.statuscode418.attrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKnB5NnAKjyetB78PKgbLDPaNYCCMKrQ',
    appId: '1:138006115795:ios:2b7b0a87f237ecbed3ab26',
    messagingSenderId: '138006115795',
    projectId: 'eentrack-version-2',
    storageBucket: 'eentrack-version-2.appspot.com',
    iosBundleId: 'com.statuscode418.attrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2mTq1u8uig8HIWpHjDF30E-_gUs6wi4',
    appId: '1:138006115795:web:d7af9690e91e3c8ad3ab26',
    messagingSenderId: '138006115795',
    projectId: 'eentrack-version-2',
    authDomain: 'eentrack-version-2.firebaseapp.com',
    storageBucket: 'eentrack-version-2.appspot.com',
  );
}
